// Code generated by gen-lua-help; DO NOT EDIT.

package scripting

// LuaScriptingReference is the auto-generated Lua API reference used by --agent-help.
const LuaScriptingReference = `## Eval: Lua Scripting Interface

Sandboxed Lua VM (base/table/string/math only — no os/io/debug).
Each invocation is stateless. Last expression is JSON-serialized to stdout.
Errors go to stderr, exit 1. Use pcall() for recovery.

### Session Discovery

session(id) -> session|nil
  Get a single session by ID, or nil if not found.

sessions([{status}]) -> []session
  List active sessions. Optional filter: status="idle"|"working".

wait(id, [{timeout}]) -> session
  Block until session becomes idle. Default timeout 300s.

### Send & Wait

cancel_queue(id, index)
  Cancel a queued message by 1-based index.

queue(id, msg)
  Queue message for delivery when session becomes idle.

send(id, msg, [{wait, timeout}])
  Send message to session's tmux pane. Options: wait="idle"|"working", timeout=N.

### Lifecycle

kill(id)
  Send SIGTERM to session and clean up.

spawn(cwd, [{tmux_session, message}]) -> {session_id, pane_id}
  Spawn a new Claude session in the given directory. Blocks up to 30s.

### Orchestrator

register_orchestrator(id)
  Exclude session from sessions() results. For orchestrator self-exclusion.

unregister_orchestrator(id)
  Re-include a previously excluded session in sessions() results.

### Features

cancel_commit_done(id)
  Cancel pending commit-done auto-kill.

commit(id)
  Send /commit to session (no auto-kill).

commit_done(id)
  Send /commit and auto-kill session on completion.

diff_hunks(id) -> [{file_path, old_string, new_string, is_write}]
  Get individual diff hunks for session.

diff_stats(id) -> {filepath: {added, removed}}
  Get diff statistics per file for session.

hook_events(id) -> [{time, hook_type, effect}]
  Get hook events for session.

later(id)
  Mark session for later review.

later_kill(id)
  Mark session for later and kill its pane.

raw_transcript(id) -> []entry
  Get parsed transcript entries with index, type, content_type, summary, timestamp.

summary(id) -> {synthesized_title}|nil
  Get cached summary for session, or nil.

synthesize(id) -> {synthesized_title, from_cache}
  Generate LLM summary for session.

synthesize_all() -> [{pane_id, synthesized_title, from_cache}]
  Generate LLM summaries for all sessions.

transcript(id) -> []string
  Get user messages from session transcript.

unlater(later_id)
  Remove a Later record by its ID.

### Backlog

backlog_create(cwd, body) -> backlog
  Create a new backlog item.

backlog_delete(cwd, id)
  Delete a backlog item.

backlog_list(cwd) -> []backlog
  List all backlog items for the given working directory.

backlog_update(cwd, id, body) -> backlog
  Update an existing backlog item's body.

### Context

selected() -> string|nil
  Return session ID currently selected in TUI. Returns nil from CLI.

### Utilities

flash(msg)
  Set TUI footer flash message. In CLI, prints to stderr.

log(...)
  Print arguments to stderr (tab-separated). Not included in JSON output.

sleep(seconds)
  Pause execution for the given number of seconds.

toast(msg)
  Add entry to TUI toast overlay. In CLI, prints to stderr.

### Session Fields

id, pane_id, project, cwd, git_branch, tmux_session, tmux_window, tmux_pane, pid, status, first_message, last_user_message, synthesized_title, custom_title, permission_mode, stop_reason, is_waiting, compact_count, commit_done_pending, queue_pending, created_at, last_changed, display_name

### Backlog Fields

id, body, cwd, project, title, created_at, updated_at
`
