// Code generated by gen-lua-help; DO NOT EDIT.

package scripting

// LuaScriptingReference is the auto-generated Lua API reference used by --agent-help.
const LuaScriptingReference = `## Eval: Lua Scripting Interface

Sandboxed Lua VM (base/table/string/math only — no os/io/debug).
Each invocation is stateless. Last expression is JSON-serialized to stdout.
Errors go to stderr, exit 1. Use pcall() for recovery.

### Session Discovery

session(id) -> session|nil
  Get a single session by ID, or nil if not found.

sessions([{status}]) -> []session
  List active sessions. Optional filter: status="idle"|"working".

wait(id, [{mode, timeout}]) -> session
  Block until session reaches a state. mode="idle" (default), "working", or "cycle"
  (waits for working then idle — useful right after sending a slash command).
  Default timeout 300s.

### Send & Wait

cancel_queue(id, index) -> {ok, operation, target}
  Cancel a queued message by 1-based index.

queue(id, msg) -> {ok, operation, target}
  Queue message for delivery when session becomes idle.

send(id, msg, [{wait, timeout}]) -> {ok, operation, target, [session]}
  Send message to session's tmux pane. Options: wait="idle"|"working"|"cycle", timeout=N.
  "cycle" waits until the session enters working then returns to idle (guards against
  pre-work false-idle right after sending a slash command). Returns a structured
  result; when wait is set, the resolved session is attached under "session".

### Lifecycle

kill(id) -> {ok, operation, target}
  Send SIGTERM to session and clean up.

spawn(cwd, [{provider, tmux_session, message, split_from_pane}]) -> {ok, operation, session_id, pane_id}
  Spawn a new session in the given directory. Blocks up to 30s. provider selects
  the agent ("claude" default, "codex", …); unknown providers are rejected by the
  daemon's provider registry. If split_from_pane is set (e.g. "%145"), the new
  pane is split next to it in the same tmux window; otherwise a new window is created.

### Orchestrator

register_orchestrator(id) -> {ok, operation, target}
  Exclude session from sessions() results. For orchestrator self-exclusion.

unregister_orchestrator(id) -> {ok, operation, target}
  Re-include a previously excluded session in sessions() results.

### Features

attention() -> {items=[]item, watches=[]watch}
  The attention inbox: unresolved attention items (with description, any
  recommendation, and the causal audit chain) plus all known watches.

cancel_commit_done(id) -> {ok, operation, target}
  Cancel pending commit-done auto-kill.

commit(id) -> {ok, operation, target}
  Send /commit to session (no auto-kill).

commit_done(id) -> {ok, operation, target}
  Send /commit and auto-kill session on completion.

diff_hunks(id) -> [{file_path, old_string, new_string, is_write}]
  Get individual diff hunks for session.

diff_stats(id) -> {filepath: {added, removed}}
  Get diff statistics per file for session.

hook_events(id) -> [{time, hook_type, effect}]
  Get hook events for session.

later(id) -> {ok, operation, target}
  Mark session for later review.

later_kill(id) -> {ok, operation, target}
  Mark session for later and kill its pane.

plan_actions(steps) -> plan
  Dry-run a batch of actions (W8): validates fail-fast (unknown session,
  capability-gated op, malformed step), resolves targets against the live
  fleet, and returns the ordered plan with a risk class per step (Decision 5)
  and approval points marked. Executes NOTHING. Steps use the shared schema:
  {op="send|queue|tag|note|later|kill|commit|spawn|wait", session_id=..., ...}.

queue_commit_done(id) -> {ok, operation, target}
  Queue /commit behind any pending work and auto-kill on commit. Returns
  immediately — unlike commit_done(), this does not type into the pane right
  away, so it's safe to call right after send(id, "/foo") without waiting for
  /foo to finish. The auto-kill watcher tolerates intermediate working→idle
  cycles and only resolves on an actual commit.

raw_transcript(id) -> []entry
  Get parsed transcript entries with index, type, content_type, summary, timestamp.

run_actions(steps, [{on_error, resume_of}]) -> result
  Execute a batch of actions as ONE unit (W8): validates exactly like
  plan_actions (an invalid batch is rejected whole, never half-executed),
  then runs steps sequentially and returns one ActionReceipt per step.
  Partial failure: on_error="stop" (default) skips the steps after a failure
  and returns them verbatim in result.remainder — resume by resubmitting the
  remainder with resume_of=result.batch_id. on_error="continue" runs every
  step regardless.

runbook_explain(name) -> runbook
  Explain a runbook without executing ANY of it (not even the build phase):
  metadata, declared params (required marked), and declared action classes.

runbook_plan(name, [params]) -> plan
  Dry-run a runbook (W8): runs its side-effect-free build phase over the live
  fleet snapshot and returns the emitted batch as a plan — targets resolved,
  risk classes marked, nothing executed.

runbook_run(name, [params]) -> result
  Execute a runbook: the build phase emits a batch which then rides the same
  action pipeline as run_actions — per-step ActionReceipts, stop-on-failure
  with a resubmittable remainder. Structured results, not terminal side
  effects.

runbooks() -> []runbook
  List the named runbooks (~/.spirit/runbooks/*.lua plus builtins): name,
  description, declared params and action classes. A runbook's execute phase
  emits a batch that rides the same action pipeline as run_actions.

set_note(id, note) -> {ok, operation, target}
  Set a session's note (persisted and broadcast to subscribers). An empty string
  clears it.

set_tags(id, tags) -> {ok, operation, target}
  Replace a session's tags with the given array (persisted and broadcast to
  subscribers). Passing an empty table clears the tags.

summary(id) -> {synthesized_title}|nil
  Get cached summary for session, or nil.

synthesize(id) -> {synthesized_title, from_cache}
  Generate LLM summary for session.

synthesize_all() -> [{pane_id, synthesized_title, from_cache}]
  Generate LLM summaries for all sessions.

transcript(id) -> []string
  Get user messages from session transcript.

unlater(later_id) -> {ok, operation, target}
  Remove a Later record by its ID.

unwatch(watch_id) -> {ok, operation, target}
  Cancel a live reactive watch by its watch_id.

watch(id, [{condition, response, project, action_id, expires_in_minutes, cooldown_seconds, max_firings, llm_budget}]) -> watch
  Create a reactive watch on a session (W7). Defaults: condition
  "completed_turn", response "inspect_and_recommend", 24h expiry, 60s
  cooldown, 20 firings. Pass "" as id with opts.project for a project-wide
  watch, or "" with no project for fleet-wide. opts.action_id (with condition
  "action_reconciled") anchors the watch to ONE action — e.g. a batch step's
  action_id — firing exactly when that action's delivery/failure signal lands.
  While a TUI client is attached, Spirit reacts: inbox records, notify raises
  one coalesced notification, inspect_and_recommend attaches a bounded LLM
  proposal to the attention item.

watches() -> []watch
  List reactive watches: scope, condition, response, FSM state, firing/LLM
  budgets, last outcome. Includes recently expired/cancelled/failed watches.

### Backlog

backlog_create(cwd, body) -> backlog
  Create a new backlog item.

backlog_delete(cwd, id)
  Delete a backlog item.

backlog_list(cwd) -> []backlog
  List all backlog items for the given working directory.

backlog_update(cwd, id, body) -> backlog
  Update an existing backlog item's body.

### Context

selected() -> string|nil
  Return session ID currently selected in TUI. Returns nil from CLI.

### Utilities

auto_jump(id)
  Advance TUI selection past the given session (to the next idle/oldest).
  Honors the autoJump pref. Takes effect after the script returns.

flash(msg)
  Set TUI footer flash message. In CLI, prints to stderr.

log(...)
  Print arguments to stderr (tab-separated). Not included in JSON output.

sleep(seconds)
  Pause execution for the given number of seconds.

toast(msg)
  Add entry to TUI toast overlay. In CLI, prints to stderr.

### Session Fields

id, pane_id, project, project_code, cwd, git_branch, tmux_session, tmux_window, tmux_pane, pid, status, first_message, last_user_message, synthesized_title, custom_title, permission_mode, stop_reason, is_waiting, compact_count, commit_done_pending, queue_pending, created_at, last_changed, display_name

### Backlog Fields

id, body, cwd, project, title, created_at, updated_at
`
