// Code generated by gen-lua-help; DO NOT EDIT.

package scripting

import lua "github.com/yuin/gopher-lua"

func registerAllAPIs(L *lua.LState, deps Deps) {
	L.SetGlobal("session", L.NewFunction(luaSession(deps)))
	L.SetGlobal("sessions", L.NewFunction(luaSessions(deps)))
	L.SetGlobal("wait", L.NewFunction(luaWait(deps)))
	L.SetGlobal("cancel_queue", L.NewFunction(luaCancelQueue(deps)))
	L.SetGlobal("queue", L.NewFunction(luaQueue(deps)))
	L.SetGlobal("send", L.NewFunction(luaSend(deps)))
	L.SetGlobal("kill", L.NewFunction(luaKill(deps)))
	L.SetGlobal("spawn", L.NewFunction(luaSpawn(deps)))
	L.SetGlobal("register_orchestrator", L.NewFunction(luaRegisterOrchestrator(deps)))
	L.SetGlobal("unregister_orchestrator", L.NewFunction(luaUnregisterOrchestrator(deps)))
	L.SetGlobal("cancel_commit_done", L.NewFunction(luaCancelCommitDone(deps)))
	L.SetGlobal("commit", L.NewFunction(luaCommit(deps)))
	L.SetGlobal("commit_done", L.NewFunction(luaCommitDone(deps)))
	L.SetGlobal("diff_hunks", L.NewFunction(luaDiffHunks(deps)))
	L.SetGlobal("diff_stats", L.NewFunction(luaDiffStats(deps)))
	L.SetGlobal("hook_events", L.NewFunction(luaHookEvents(deps)))
	L.SetGlobal("later", L.NewFunction(luaLater(deps)))
	L.SetGlobal("later_kill", L.NewFunction(luaLaterKill(deps)))
	L.SetGlobal("raw_transcript", L.NewFunction(luaRawTranscript(deps)))
	L.SetGlobal("summary", L.NewFunction(luaSummary(deps)))
	L.SetGlobal("synthesize", L.NewFunction(luaSynthesize(deps)))
	L.SetGlobal("synthesize_all", L.NewFunction(luaSynthesizeAll(deps)))
	L.SetGlobal("transcript", L.NewFunction(luaTranscript(deps)))
	L.SetGlobal("unlater", L.NewFunction(luaUnlater(deps)))
	L.SetGlobal("backlog_create", L.NewFunction(luaBacklogCreate(deps)))
	L.SetGlobal("backlog_delete", L.NewFunction(luaBacklogDelete(deps)))
	L.SetGlobal("backlog_list", L.NewFunction(luaBacklogList(deps)))
	L.SetGlobal("backlog_update", L.NewFunction(luaBacklogUpdate(deps)))
	L.SetGlobal("selected", L.NewFunction(luaSelected(deps)))
	L.SetGlobal("flash", L.NewFunction(luaFlash(deps)))
	L.SetGlobal("log", L.NewFunction(luaLog(deps)))
	L.SetGlobal("sleep", L.NewFunction(luaSleep(deps)))
	L.SetGlobal("toast", L.NewFunction(luaToast(deps)))
}
